# This workflow will run docker multi platform build
# It runs on merges to master and pull requests because it is very long

name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    # branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64 ,linux/arm64, linux/386, linux/arm/v7 ] #,linux/arm/v6
        policy: [ "manylinux2014" ]
 
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: matrix.platform != 'linux/amd64' && matrix.platform != 'linux/386'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          # buildkitd-flags: --debug

      - name: Build Release Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.${{ matrix.policy }}
          platforms: ${{ matrix.platform }} #linux/amd64 #,linux/arm64,linux/386 #,linux/arm/v7 #,linux/arm/v6
          push: false
          tags: |
            icloudpd/${{ matrix.policy }}_${{ matrix.platform }}:latest
          outputs: type=docker,dest=/tmp/${{ matrix.policy }}_${{ matrix.platform }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: /tmp/${{ matrix.policy }}_${{ matrix.platform }}.tar

  combine:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: images
          path: /tmp
      - name: Load image
        run: |
          cat /tmp/*.tar | docker load
          docker image ls -a
      # - name: Create Manifest List
      #   run: |
      #     docker create manifest
      # - name: Deploy
      #   run: |
      #     docker publish