# This workflow will run docker multi platform build
# It runs on merges to master and pull requests because it is very long

name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    # branches: [ main ]
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64 ,linux/arm64, linux/386, linux/arm/v7 ] #,linux/arm/v6
        policy: [ "manylinux2014" ]
 
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          # buildkitd-flags: --debug

      - name: Build Release Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.${{ matrix.policy }}
          platforms: ${{ matrix.platform }} #linux/amd64 #,linux/arm64,linux/386 #,linux/arm/v7 #,linux/arm/v6
          push: false
          tags: |
            icloudpd/${{ matrix.policy }}_${{ matrix.platform }}:latest
